services:
  - type: worker
    name: autofilterbot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    autoDeploy: true
    envVars:
      # Required Variables
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: ADMINS
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_NAME
        value: AutoFilterBot
      - key: LOG_CHANNEL
        sync: false
      
      # Optional Variables
      - key: WEB_SUPPORT
        value: "True"
      - key: CHANNELS
        sync: false
      - key: AUTH_CHANNEL
        sync: false
      - key: SUPPORT_CHAT
        value: DevilServers
      - key: PICS
        sync: false
      - key: COLLECTION_NAME
        value: Telegram_files
      - key: MAX_RIST_BTNS
        value: "10"
      - key: CUSTOM_FILE_CAPTION
        sync: false
      - key: IMDB
        value: "True"
      - key: PM_IMDB
        value: "True"
      - key: IMDB_TEMPLATE
        sync: false
      - key: IMDB_DELET_TIME
        value: "300"
      - key: SINGLE_BUTTON
        value: "True"
      - key: PROTECT_CONTENT
        value: "False"
      - key: PMFILTER
        value: "True"
      - key: G_FILTER
        value: "True"
      - key: BUTTON_LOCK
        value: "True"
      - key: P_TTI_SHOW_OFF
        value: "True"
      - key: SHORT_URL
        sync: false
      - key: SHORT_API
        sync: false
